name: Deploy MkDocs Documentation

# Trigger this workflow only when building the main branch
on:
  push:
    branches: [main]

# Needed to push to gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material theme, add Mermaid2 and Minify plugins
        run: |
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-mermaid2-plugin \
            mkdocs-minify-plugin

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
