name: spell-check
on:
  - push
  - pull_request
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spell Check
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespellignore
          skip: binaries,ci,circuits,extras,images,sounds,stl
